name: fluent_data_grid
description: Fluent UI-style DataGrid for Flutter (Windows/macOS)
version: 0.1.4
homepage: https://github.com/your-org/fluent_data_grid
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter: { sdk: flutter }
  fluent_ui: ^4.13.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: false
